# Generated by Django 5.2 on 2026-02-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
