# Generated by Django 5.2 on 2026-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='animal_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Nom de l'animal concerné"),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('adoption', "Demande d'adoption"), ('abandon', 'Demande de prise en charge / Abandon'), ('fa', "Devenir Famille d'Accueil / Bénévolat"), ('autre', 'Autre question / Renseignement')], default='autre', max_length=20, verbose_name='Motif de contact'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Votre message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Sujet'),
        ),
    ]
