# Generated by Django 5.2 on 2026-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_animal_name_contactmessage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(blank=True, choices=[('adoption', "Demande d'adoption"), ('abandon', 'Demande de prise en charge / Abandon'), ('fa', "Devenir Famille d'Accueil / Bénévolat"), ('autre', 'Autre question / Renseignement')], default='autre', max_length=20, verbose_name='Motif de contact'),
        ),
    ]
