# Generated by Django 5.2 on 2026-02-09 12:59

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("file", models.FileField(upload_to="uploads/%Y/%m/")),
                ("alt_text", models.CharField(blank=True, default="", max_length=512)),
                ("caption", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wp_post_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "original_url",
                    models.URLField(blank=True, default="", max_length=1024),
                ),
            ],
            options={
                "verbose_name_plural": "media",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "wp_term_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(db_index=True, max_length=1024, unique=True),
                ),
                ("new_path", models.CharField(max_length=1024)),
                ("is_permanent", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["old_path"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "wp_term_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "wp_term_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=1024)),
                ("target", models.CharField(blank=True, default="", max_length=50)),
                (
                    "css_classes",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "wp_post_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="blog.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="blog.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(max_length=512, unique=True)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, default=""),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("private", "Privé"),
                            ("trash", "Corbeille"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("template", models.CharField(blank=True, default="", max_length=255)),
                ("menu_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, default="", max_length=512)),
                ("seo_description", models.TextField(blank=True, default="")),
                (
                    "wp_post_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="blog.page",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(max_length=512, unique=True)),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, default=""),
                ),
                ("excerpt", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("pending", "En attente"),
                            ("private", "Privé"),
                            ("trash", "Corbeille"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("seo_title", models.CharField(blank=True, default="", max_length=512)),
                ("seo_description", models.TextField(blank=True, default="")),
                (
                    "wp_post_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.category"
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_for_posts",
                        to="blog.media",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="PluginData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plugin_name", models.CharField(db_index=True, max_length=255)),
                ("source_table", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_data",
                        to="blog.page",
                    ),
                ),
                (
                    "related_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_data",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "plugin data",
                "ordering": ["plugin_name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                (
                    "author_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("author_url", models.URLField(blank=True, default="")),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approuvé"),
                            ("pending", "En attente"),
                            ("spam", "Spam"),
                            ("trash", "Corbeille"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wp_comment_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
