# Generated by Django 5.2 on 2026-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="mime_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
