# Generated by Django 5.2 on 2026-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_media_mime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(max_length=512, upload_to="uploads/%Y/%m/"),
        ),
    ]
