# Generated by Django 5.2 on 2026-02-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_media_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
            },
        ),
        migrations.AlterModelOptions(
            name="media",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Media",
                "verbose_name_plural": "Medias",
            },
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["name"],
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["position"],
                "verbose_name": "Element de menu",
                "verbose_name_plural": "Elements de menu",
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["menu_order", "title"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.AlterModelOptions(
            name="plugindata",
            options={
                "ordering": ["plugin_name", "-created_at"],
                "verbose_name": "Donnee plugin",
                "verbose_name_plural": "Donnees plugins",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="redirect",
            options={
                "ordering": ["old_path"],
                "verbose_name": "Redirection",
                "verbose_name_plural": "Redirections",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Etiquette",
                "verbose_name_plural": "Etiquettes",
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="linked_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="blog.category",
                verbose_name="Categorie liee",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="linked_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="blog.page",
                verbose_name="Page liee",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="linked_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="blog.post",
                verbose_name="Article lie",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="css_classes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Classes CSS"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="blog.menuitem",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[("", "Meme fenetre"), ("_blank", "Nouvelle fenetre")],
                default="",
                max_length=50,
                verbose_name="Ouvrir dans",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Laisser vide si un article, page ou categorie est selectionne.",
                max_length=1024,
                verbose_name="URL personnalisee",
            ),
        ),
    ]
