# Generated by Django 5.2.11 on 2026-02-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_add_menuitem_linked_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="animal_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nom de l'animal"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="breed",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Race"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="foster_family",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Famille d'accueil"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="identification",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Identification electronique",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_adoptable",
            field=models.BooleanField(default=False, verbose_name="Adoptable"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_sterilized",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Sterilise/Castre"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_vaccinated",
            field=models.BooleanField(blank=True, null=True, verbose_name="Vaccine"),
        ),
        migrations.AddField(
            model_name="post",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("", "---"), ("male", "Mâle"), ("femelle", "Femelle")],
                default="",
                max_length=10,
                verbose_name="Sexe",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="species",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---"),
                    ("chien", "Chien"),
                    ("chat", "Chat"),
                    ("rongeur", "Rongeur"),
                    ("autre", "Autre"),
                ],
                default="",
                max_length=20,
                verbose_name="Espece",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Poids (kg)",
            ),
        ),
    ]
