# Generated by Django 5.2 on 2026-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_animal_name_post_birth_date_post_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adoption_status',
            field=models.CharField(choices=[('adoptable', 'Adoptable'), ('reserve', 'Réservé'), ('recherche_fa', 'Recherche FA'), ('adopte', 'Adopté')], default='adoptable', max_length=20, verbose_name="Statut d'adoption"),
        ),
        migrations.AddField(
            model_name='post',
            name='housing_requirement',
            field=models.CharField(choices=[('indifferent', 'Indifférent (Maison ou Appartement)'), ('maison', 'Maison obligatoire'), ('appartement', 'Appartement possible')], default='indifferent', max_length=20, verbose_name="Type d'habitat requis"),
        ),
        migrations.AddField(
            model_name='post',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Urgence / À la une'),
        ),
        migrations.AddField(
            model_name='post',
            name='ok_cats',
            field=models.CharField(blank=True, choices=[('', 'Inconnu / À tester'), ('oui', 'Oui'), ('non', 'Non')], default='', max_length=10, verbose_name='Ok Chats'),
        ),
        migrations.AddField(
            model_name='post',
            name='ok_children',
            field=models.CharField(blank=True, choices=[('', 'Inconnu / À tester'), ('oui', 'Oui'), ('non', 'Non')], default='', max_length=10, verbose_name='Ok Enfants'),
        ),
        migrations.AddField(
            model_name='post',
            name='ok_dogs',
            field=models.CharField(blank=True, choices=[('', 'Inconnu / À tester'), ('oui', 'Oui'), ('non', 'Non')], default='', max_length=10, verbose_name='Ok Chiens'),
        ),
    ]
