# Generated by Django 5.2 on 2026-08-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_adoption_status_post_housing_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adoption_date',
            field=models.DateField(blank=True, help_text="Date d'adoption définitive", null=True, verbose_name="Date d'adoption"),
        ),
    ]
