# Generated by Django 5.2 on 2026-08-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_adoption_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
            ],
            options={
                'verbose_name': 'Fiche animal',
                'verbose_name_plural': "Animaux à l'adoption",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles & Actualités',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.post',),
        ),
    ]
