# Generated by Django 5.2 on 2026-08-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_animal_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(default='Association Rêves de Chiens', max_length=255, verbose_name="Nom de l'association")),
                ('tagline', models.CharField(blank=True, default='Refuge Solidaire pour chiens, chats & rongeurs', max_length=512, verbose_name='Slogan / Sous-titre')),
                ('contact_email', models.EmailField(default='contact@revesdechiens.fr', help_text='Email affiché publiquement et utilisé pour recevoir les messages du formulaire de contact.', max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, default='01 23 45 67 89', help_text='Numéro affiché (ex: 01 23 45 67 89 ou 06 12 34 56 78).', max_length=50, verbose_name='Téléphone')),
                ('opening_hours', models.CharField(blank=True, default='Permanence téléphonique du lundi au samedi 9h-18h', help_text='Horaires ou indications de permanence affichés sur la page contact.', max_length=255, verbose_name='Disponibilités / Permanence')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse / Rue')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('region_coverage', models.CharField(blank=True, default='Île-de-France & environs', help_text="Zone géographique d'intervention affichée dans le pied de page et les mentions.", max_length=255, verbose_name="Zone d'intervention couverte")),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', verbose_name='Lien Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/refuge_reves_de_chiens/', verbose_name='Lien Instagram')),
                ('instagram_username', models.CharField(blank=True, default='@refuge_reves_de_chiens', max_length=100, verbose_name='Identifiant Instagram')),
                ('tiktok_url', models.URLField(blank=True, default='', verbose_name='Lien TikTok')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='Lien YouTube')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Lien X / Twitter')),
                ('linkedin_url', models.URLField(blank=True, default='', verbose_name='Lien LinkedIn')),
                ('helloasso_url', models.URLField(blank=True, default='https://www.helloasso.com/associations/reves-de-chiens', help_text='Lien vers votre formulaire officiel de dons ou adhésions HelloAsso.', verbose_name='Lien HelloAsso (Dons & Adhésions)')),
                ('siret', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro SIRET')),
                ('rna_number', models.CharField(blank=True, default='W751234567', max_length=50, verbose_name='Numéro RNA')),
                ('legal_status', models.CharField(blank=True, default="Association reconnue d'intérêt général", max_length=255, verbose_name='Statut / Reconnaissance')),
                ('footer_custom_text', models.TextField(blank=True, default='', help_text='Message ou mention additionnelle affichée dans le pied de page.', verbose_name='Texte personnalisé pied de page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du Site',
                'verbose_name_plural': 'Paramètres Généraux du Site',
            },
        ),
    ]
