# Generated by Django 5.2 on 2026-08-27 14:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_adoptiontariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brevo_sender_email',
            field=models.EmailField(blank=True, default='', help_text='Email utilisé comme expéditeur des accusés de réception Brevo. Si vide, utilise la configuration système.', max_length=254, verbose_name="Email d'expédition des notifications"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_main_label',
            field=models.CharField(default='Adopter un animal', help_text="Libellé du bouton d'action principal (menu mobile et navigation).", max_length=100, verbose_name='Texte du bouton CTA principal'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_template_abandon',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text="Corps HTML de l'email automatique envoyé après une demande de prise en charge. Variables disponibles : {{ name }}, {{ email }}, {{ phone }}, {{ animal_name }}, {{ subject }}.", verbose_name='Template Email - Accusé Prise en charge / Abandon (HTML)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_template_adoption',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text="Corps HTML de l'email automatique envoyé après une demande d'adoption. Variables disponibles : {{ name }}, {{ email }}, {{ phone }}, {{ animal_name }}, {{ subject }}.", verbose_name='Template Email - Accusé et Questionnaire Adoption (HTML)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_template_fa',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', help_text="Corps HTML de l'email automatique envoyé après une candidature FA. Variables disponibles : {{ name }}, {{ email }}, {{ phone }}, {{ animal_name }}, {{ subject }}.", verbose_name="Template Email - Accusé Famille d'Accueil / Bénévolat (HTML)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_animals_count',
            field=models.PositiveIntegerField(default=6, help_text="Nombre de fiches d'animaux à l'adoption visibles sur la page d'accueil.", verbose_name="Nombre d'animaux affichés en accueil"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=10, help_text='Nombre de fiches ou articles affichés par page dans le catalogue, les catégories et les recherches.', verbose_name="Nombre d'éléments par page (pagination)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_enabled',
            field=models.BooleanField(default=True, help_text="Cocher pour afficher le bandeau supérieur d'annonce au-dessus de l'en-tête.", verbose_name="Barre d'annonce (Top Bar) activée"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='topbar_text',
            field=models.CharField(blank=True, default="Refuge solidaire 100% Familles d'Accueil · Adoptez, sauvez une vie", help_text="Message affiché dans le bandeau supérieur d'annonce.", max_length=512, verbose_name="Texte de la barre d'annonce"),
        ),
    ]
