# Generated by Django 5.2 on 2026-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_seed_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text="Logo officiel de l'association (PNG, SVG, WEBP ou JPG). Si vide, le logo par défaut est utilisé.", null=True, upload_to='site/', verbose_name='Logo officiel du site'),
        ),
    ]
